### ISSUE TITLE
Something went wrong when re-linking

### ISSUE THREAD

**Issue by chriswalker01** [openhab/openhab-google-assistant#103]
Hi,
I've been using this for about 18 months and love it, but today I tried to add a new item. I then told Google to do a sync, but it said there was an error.
I decided to unlink and relink it within the Google Home. When I select my Openhab test app, it prompts me for an account to link and shows my gmail address. When I select "Link Accounts", it says "Something went wrong".

I remove the new item from Openhab, but that didn't help. It doesn't appear to be finding my Openhab server. In the past, I was asked to select the gmail address to link, but was taken straight to the login page of my Openhab server. Has something changed with the way Google authenticates or something?

**Comment by GravityRZ** [comment]
i have the same problem. added a device, could not sync
i threw everything away, tried to couple again with openhab but i get the error something went wrong.

the strange thing is in the beginning i got the oauth2 screen but now it instantly sys connected and after that something went wrong.

really buggy.
everything is working perfectly in openhab and cloud connection is working as well
i tried another device(thought it was a caching problem) but exactly the same issue

this is between google(home/assistant) and openhab but i think google does not even look at openhab because of the quick response

well siri is working perfectly so if they do not solve this fast i will through out my sonos and start using homepod

**Comment by juanhaywood** [comment]
Was running into the same issue. The solution for me was to first unlink the previous authorization on Google. You can do that here: https://goo.gle/2N1c1pR

**Comment by marziman** [comment]
Closing, please reopen if still an issue.
