### ISSUE TITLE
"Fahrenheit" breake the thermostat in GH app

### ISSUE THREAD

**Issue by kandersen01** [openhab/openhab-google-assistant#126]
It seems like after GA integration v.2 has been merged, using "Fahrenheit" in the Thermostat tag, will break the thermostat values wihtin the Google Home app.

See more info in here:
https://community.openhab.org/t/openhab-google-assistant-integration-v2-0/85573/84

**Comment by skimdankish** [comment]
I copied your commits into my cloud function source and it's reporting the correct temperature in the correct unit (F).  However, still unable to send command to setpoint.

It's saying "two thermostats are not available" when adjusting my First Floor Thermostat and throwing this in the logs from a single invocation:

`commands.ThermostatTemperatureSetpoint: {"devices":[{"customData":{"itemTag":"Thermostat","itemType":"Group","openhabVersion":"2.4.0"},"id":"g_HK_FF_TSTAT"}],"params":{"thermostatTemperatureSetpoint":22.77777862548828}}`

`openhabGoogleAssistant - commands.ThermostatTemperatureSetpoint: {"devices":[{"customData":{"itemTag":"Thermostat","itemType":"Group","openhabVersion":"2.4.0"},"id":"g_HK_FF_TSTAT"}],"params":{"thermostatTemperatureSetpoint":73}}`

I think it's happening twice because the handleExecute console log is pulling this:

`openhabGoogleAssistant - handleExecute - commands: [{"devices":[{"customData":{"itemTag":"Thermostat","itemType":"Group","openhabVersion":"2.4.0"},"id":"g_HK_FF_TSTAT"}],"execution":[{"command":"action.devices.commands.ThermostatTemperatureSetpoint","params":{"thermostatTemperatureSetpoint":22.77777862548828}}]},{"devices":[{"customData":{"itemTag":"Thermostat","itemType":"Group","openhabVersion":"2.4.0"},"id":"g_HK_FF_TSTAT"}],"execution":[{"command":"action.devices.commands.ThermostatTemperatureSetpoint","params":{"thermostatTemperatureSetpoint":73}}]}]`

I'll continue to look into as I have time.  I also did a clean pull and made only this commit adjustment to avoid any confusion with my own tests/changes.

**Comment by michikrug** [comment]
@skimdankish Thanks for checking. I wasn't aware that setting the setpoint is also broken. Will test this again, too.

**Comment by michikrug** [comment]
Found the issue and added a fix

**Comment by skimdankish** [comment]
That did it, but it's still duplicating the command in my logs (and thus saying "two thermostats").

handleQuery:
`openhabGoogleAssistant - handleQuery - devices: [{"customData":{"itemTag":"Thermostat","itemType":"Group","openhabVersion":"2.4.0"},"id":"g_HK_SF_TSTAT"},{"customData":{"itemTag":"Thermostat","itemType":"Group","openhabVersion":"2.4.0"},"id":"g_HK_SF_TSTAT"}]`

HandleExecute:
`openhabGoogleAssistant - handleExecute - commands: [{"devices":[{"customData":{"itemTag":"Thermostat","itemType":"Group","openhabVersion":"2.4.0"},"id":"g_HK_SF_TSTAT"},{"customData":{"itemTag":"Thermostat","itemType":"Group","openhabVersion":"2.4.0"},"id":"g_HK_SF_TSTAT"}],"execution":[{"command":"action.devices.commands.ThermostatTemperatureSetpoint","params":{"thermostatTemperatureSetpoint":23.33333396911621}}]}]`

Command:
`openhabGoogleAssistant - commands.ThermostatTemperatureSetpoint: {"devices":[{"customData":{"itemTag":"Thermostat","itemType":"Group","openhabVersion":"2.4.0"},"id":"g_HK_SF_TSTAT"},{"customData":{"itemTag":"Thermostat","itemType":"Group","openhabVersion":"2.4.0"},"id":"g_HK_SF_TSTAT"}],"params":{"thermostatTemperatureSetpoint":23.33333396911621}}`

I'm going to take a look a little later, it started after I added Commit 4d5be34 (which fixed Fahrenheit).

**Comment by michikrug** [comment]
But the "handleExecute " output is the plain command that is received from Google. So it seems an issue there. Do you have multiple devices with the same id somehow?

**Comment by skimdankish** [comment]
I checked the home control section and saw that it was 58 - it should have been 29.  I unlinked/relinked the service and it works perfectly now with that latest commit.

**Comment by hotrodwinston** [comment]
any news?

**Comment by wtf911** [comment]
If I'm using openhab 2.5.0 stable with myopenhab will I need to update my openhab to get this fix? Or will the "myopenhab website/platform" need to be updated on openhabs end? Aka if this something I do on my end or they do on their end since I use the free myopenhab site.
