### ISSUE TITLE
Blinds issue

### ISSUE THREAD

**Issue by scavenrage** [openhab/openhab-google-assistant#133]
Just tested the my blinds with the new tags method, with the "inverted" option.
When I say "set bedroom blind to 45%" the percentage now arrive correctly in openhab.
But when I say "open" or close the commands are inverted:
example
"close bedroom blind"
in the console appears "Item 'TappCameraTarget' received command UP
and 
"open bedroom blind"
in the console appears "Item 'TappCameraTarget' received command DOWN

Thanks,

**Comment by michikrug** [comment]
Thanks for reporting, will have a look.

**Comment by michikrug** [comment]
To recap...

Google world says: xx% is the percentage of how much a blind is opened
-> "close" translates to 0%
-> "open" translates to 100%

openHAB world says: xx% is the percentage of how much a blind is closed
-> "down" translates to 100%
-> "up" translates to 0%

Therefore, by default the percentage is always inverted, so that "close" becomes "down".
If a user does not want this inversion, the `inverted=true` option can be set.
But this also causes "close" being inverted to "up" and "open" becoming "down".

Since Google only tells the open percentage (and not the verb "close" or "down"), we can not differentiate between saying "set blind to 100%" or "open blind".
Therefore, we are not able to "not invert" the verbs, if the users chooses to invert the numbers.

**Comment by scavenrage** [comment]
Ok, so I will continue to use a rule to invert only the values from 1 to 99% :D. Thank you very much for your work and your support!
