### ISSUE TITLE
Thermostat setpoint / low / high

### ISSUE THREAD

**Issue by kpanchen** [openhab/openhab-google-assistant#148]
Currently control items on Thermostat group requires setpoint item and has two optional as low and high however they are mutually exclusive. Technically it is possible to have all three items but I don't see how that could work. In my case Lennox use low / high and no way to set single set point. Rather this has to be explained in documentation or option make exclusive somehow.

**Comment by michikrug** [comment]
It is documented (a bit wrong - humidity instead of the correct temperature) here:
https://github.com/openhab/openhab-google-assistant#thermostats

(Optional) Temperature Setpoint High: Number. { ga="thermostatTemperatureSetpointHigh" }
(Optional) Temperature Setpoint Low: Number. { ga="thermostatTemperatureSetpointLow" }

**Comment by kpanchen** [comment]
I know about first one, it is defined correctly in my config.
As for the second one I did exactly that and it seems that works fine, maybe what's required is just to mention this in documentation to avoid confusion. If that's the case I can close the issue!

And thank you for all the work you've done on the GA, really impressive!
