### ISSUE TITLE
Support for custom responses 

### ISSUE THREAD

**Issue by velaar** [openhab/openhab-google-assistant#28]
It seems [google assistant](https://developers.google.com/actions/assistant/responses) supports custom responses. Will it be possible to implement under OpenHab/Google assistant integration?

**Comment by marziman** [comment]
Hi @velaar 
you need to know that openHAB Google Assistant is currently a "Smart Home" Action, which
is different than the "other" Actions on Google.
Maybe it makes sense to involve @kubawolanin , since we were already discussing some efforts in this direction.
@kubawolanin what do you think?

BR Mehmet

**Comment by kubawolanin** [comment]
I've implemented a simple proof of concept for integrating Dialogflow with some WebHook that would return item's state:
https://github.com/kubawolanin/openhab-dialogflow

The backend script is a Firebase Cloud Function (you can find the code [here](https://github.com/kubawolanin/openhab-dialogflow/blob/master/functions/src/index.ts)). 

This is, however, not tested by no means with any openHAB instance, as there's still a webhook with OAuth needed in order to get things working.

Cheers,
Kuba

**Comment by marziman** [comment]
@kubawolanin how should we proceed? Can you open an issue or feature request maybe explaining how this plays together? CUrrently we are using the domain of smarthome actions, which are different than other actions for Google.

Lets close this and make either a PR or re-discuss first in the forum?

**Comment by marziman** [comment]
Closing this...
