### ISSUE TITLE
Split out TargetTemperature tag for thermostats with discrete Heat/Cool setpoints

### ISSUE THREAD

**Issue by bkpsu** [openhab/openhab-google-assistant#35]
Because the CT100 (and I’m sure several other thermostats) have discrete setpoints for Heating/Cooling, using the generic “TargetTemperature” tag on both means they will both be set to the ordered temperature. This works for both modes, but doesn’t allow the use of the AUTO mode, in which the Heat/Cool setpoints define a target range rather than a discrete temperature setpoint. Instead, it would be better if there were discrete tags for Heating/Cooling setpoints.

**Comment by skimdankish** [comment]
@bkpsu 

Google has this in the traits (https://goo.gl/LyoooQ):
-thermostatTemperatureSetpointHigh
- thermostatTemperatureSetpointLow

I do not have this type of thermostat so I was not able to develop it into the code.  Within Openhab do you have these items setup?  If so, I think we need to agree on homekit tags, once this is done I think it won't be very hard to add into the code on a future update.

I kept auto (or as Google refers to: 'heatcool') in the code and also translated to Zwave - but as you say, TargetTemp is the overriding variable until we are able to have linkage between the two traits I mentioned above and whatever item-homekit tagging convention we agree to.

@marziman Who is maintaining the homekit package?  Perhaps this may be something that can be raised.  I think it best to keep it standard across all Smarthome Platforms (so at least for OH users we have a standard :D)

Ryan

**Comment by Rafal2** [comment]
can we add 
thermostatHumidityAmbient  ( Float 0-100) If available from the device. also please?
I have thermostat with Humidity value to read....

**Comment by skimdankish** [comment]
@Rafal2 

As mentioned on the community this should be fixed soon as I replaced a snippet of code and it is working for me in development.

For proper tagging convention please review the HomeKit Addon as this is the same tagging used for Google Assistant:
https://docs.openhab.org/addons/ios/homekit/readme.html

Ryan

**Comment by enderdsus7** [comment]
I also have a CT-100 thermostat and am looking for support for the two target temperatures.  I have not found any other follow-ups to this message since May 2018, and I have not found support for this in my OH2 installation.  Has this been implemented?  Can I provide any information to help the maintainer?

@skimdankish
You asked the OP if they have items for the following:
* thermostatTemperatureSetpointHigh
* thermostatTemperatureSetpointLow

For my CT100, I do have items like this.  This thermostat requires two temperature set points, one for cooling mode and one for heating mode.  Of course, if you are in heating mode or cooling mode only, the other set point is unused.  However, both need to be set for auto (heatcool) mode to work properly.  Additionally, with only one "TargetTemperature" sent from the Google assistant interface, we either have to commit to setting just one mode, or use some intermediate item and script to pass the temperature to the correct heat or cool set point based on the current mode.

I don't know how to support heatcool mode properly without having support for SetpointHigh and SetpointLow

Examples of the two items:

Number  HVAC_M_HeatSetPoint     "Heat Set [%d F]"               <temperature>   (gHVAC_M)       {channel="zwave:device:<magic_number>:node2:thermostat_setpoint_heating"}
Number  HVAC_M_CoolSetPoint     "Cool Set [%d F]"               <temperature>   (gHVAC_M)       {channel="zwave:device:<magic_number>:thermostat_setpoint_cooling"}

Glad to help provide more information about this thermostat if it is useful for developing the google assistant connector.

**Comment by bkpsu** [comment]
@michikrug @marziman - with the new actions/traits implemented, is it possible to implement @enderdsus7 solution (also listed here: https://developers.google.com/assistant/smarthome/traits/temperaturesetting.html), to have discrete High/Low temperature setpoints? For thermostats like the CT100 and any that take two separate "TargetTemperature" items for the Heat and Cool modes, it's not ideal to tag them using the single TargetTemperature tag available now.

**Comment by michikrug** [comment]
@bkpsu I will have a look after my vacation

**Comment by michikrug** [comment]
Implemented in https://github.com/openhab/openhab-google-assistant/pull/120/commits/0d7f3725da97721c679b01d48801142cbffffbea

**Comment by bkpsu** [comment]
> Implemented in [0d7f372](https://github.com/openhab/openhab-google-assistant/commit/0d7f3725da97721c679b01d48801142cbffffbea)

Thanks @michikrug - do you know if this has been pushed to the live system yet? I will test it and close as soon as I'm able to.

**Comment by michikrug** [comment]
> > Implemented in [0d7f372](https://github.com/openhab/openhab-google-assistant/commit/0d7f3725da97721c679b01d48801142cbffffbea)
> 
> Thanks @michikrug - do you know if this has been pushed to the live system yet? I will test it and close as soon as I'm able to.

It is not. And unfortunately there is also no schedule yet, since @marziman seems to be absent.

**Comment by marziman** [comment]
Iam here, just in another country :-)
Lets release it than this weekend?

**Comment by marziman** [comment]
Will be released this week.
Iam closing this...
